### PR TITLE
Update plat.conf

### PR DESCRIPTION
**Pull request by reneluria**
Add jq to the list of base software to install

### CODE REVIEW

**Comment by Neilpang** [comment]
why

**Comment by reneluria** [comment]
@Neilpang because, as it is used in several dnsapi scripts as I've seen
it is very lightweight, useful to parse json API results,
and it is available in all the platforms listed in the plat.conf 
I thought it was a good idea to add it

**Comment by Neilpang** [comment]
>> it is used in several dnsapi scripts

which one used it?

**Comment by reneluria** [comment]
oh you're right, they don't.
I saw https://github.com/acmesh-official/acme.sh/blob/master/deploy/synology_dsm.sh#L5 and didn't look further.
but do you think it could be useful ? (or better, would it harm ?)

**Comment by Neilpang** [comment]
No,  we won't import any new dependencies if not necessary.

**Comment by reneluria** [comment]
Ok, no problem, I understand.

**Pull request closed without merging**
