### PR TITLE
add --allowerasing to almalinux

### PR DESCRIPTION
**Pull request by phedoreanu**
```
sh-5.1# yum -y install curl
Last metadata expiration check: 0:00:10 ago on Sat May 13 20:38:44 2023. Error:
 Problem: problem with installed package curl-minimal-7.76.1-23.el9_2.1.aarch64
  - package curl-minimal-7.76.1-23.el9_2.1.aarch64 conflicts with curl provided by curl-7.76.1-23.el9_2.1.aarch64
  - package curl-minimal-7.76.1-23.el9.aarch64 conflicts with curl provided by curl-7.76.1-23.el9_2.1.aarch64
  - cannot install the best candidate for the job (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

### CODE REVIEW

**Comment by phedoreanu** [comment]
@Neilpang please 😄

**Comment by Neilpang** [comment]
why do you use "cronie"?  any reason?

**Comment by phedoreanu** [comment]
Yes, because the package changed. `crontabs` contains only the files, not the actual `crontab` binary.

```
$ docker run -it --rm almalinux sh
Unable to find image 'almalinux:latest' locally
latest: Pulling from library/almalinux
0855046dd749: Already exists
Digest: sha256:f47335db534a28ec4050c7e5383db4f5361d4dc684af93a5d6f09db620b7b2ea
Status: Downloaded newer image for almalinux:latest
sh-5.1# yum update
AlmaLinux 9 - AppStream                                                                                                        2.2 MB/s | 6.7 MB     00:03
AlmaLinux 9 - BaseOS                                                                                                           1.6 MB/s | 2.3 MB     00:01
AlmaLinux 9 - Extras                                                                                                            23 kB/s |  17 kB     00:00
Dependencies resolved.
Nothing to do.
Complete!
sh-5.1# yum search cron
Last metadata expiration check: 0:00:09 ago on Tue May 16 07:47:40 2023.
================================================================ Name & Summary Matched: cron =================================================================
cronie.aarch64 : Cron daemon for executing programs at set times
cronie-noanacron.aarch64 : Utility for running simple regular jobs in old cron style
crontabs.noarch : Root crontab files used to schedule the execution of programs
===================================================================== Name Matched: cron ======================================================================
cronie-anacron.aarch64 : Utility for running regular jobs
man-db-cron.noarch : Periodic update of man-db cache
rpm-cron.noarch : Create daily logs of installed packages.
```

**Comment by phedoreanu** [comment]
That's why [this build](https://github.com/acmesh-official/acmetest/actions/runs/4968817456/jobs/8893704761#step:3:194) failed with:
```
curl installed. [PASS]
Run Failed
crontab not installed------------------------------------------
```

**Pull request merged**
